version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  vendor: true
  directory: "/assets/curler"
  schedule:
    interval: "daily"
