name: Go

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - run: go vet ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - uses: golangci/golangci-lint-action@v8.0.0
